// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobile.proxies;

public class SkeletonHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject skeletonHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeMobile.SkeletonHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IsLoaded("IsLoaded"),
		IsLoaded2("IsLoaded2");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SkeletonHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SkeletonHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject skeletonHelperMendixObject)
	{
		if (skeletonHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, skeletonHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.skeletonHelperMendixObject = skeletonHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nativemobile.proxies.SkeletonHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativemobile.proxies.SkeletonHelper(context, mendixObject);
	}

	public static nativemobile.proxies.SkeletonHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativemobile.proxies.SkeletonHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of IsLoaded
	 */
	public final java.lang.Boolean getIsLoaded()
	{
		return getIsLoaded(getContext());
	}

	/**
	 * @param context
	 * @return value of IsLoaded
	 */
	public final java.lang.Boolean getIsLoaded(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsLoaded.toString());
	}

	/**
	 * Set value of IsLoaded
	 * @param isloaded
	 */
	public final void setIsLoaded(java.lang.Boolean isloaded)
	{
		setIsLoaded(getContext(), isloaded);
	}

	/**
	 * Set value of IsLoaded
	 * @param context
	 * @param isloaded
	 */
	public final void setIsLoaded(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isloaded)
	{
		getMendixObject().setValue(context, MemberNames.IsLoaded.toString(), isloaded);
	}

	/**
	 * @return value of IsLoaded2
	 */
	public final java.lang.Boolean getIsLoaded2()
	{
		return getIsLoaded2(getContext());
	}

	/**
	 * @param context
	 * @return value of IsLoaded2
	 */
	public final java.lang.Boolean getIsLoaded2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsLoaded2.toString());
	}

	/**
	 * Set value of IsLoaded2
	 * @param isloaded2
	 */
	public final void setIsLoaded2(java.lang.Boolean isloaded2)
	{
		setIsLoaded2(getContext(), isloaded2);
	}

	/**
	 * Set value of IsLoaded2
	 * @param context
	 * @param isloaded2
	 */
	public final void setIsLoaded2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isloaded2)
	{
		getMendixObject().setValue(context, MemberNames.IsLoaded2.toString(), isloaded2);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return skeletonHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativemobile.proxies.SkeletonHelper that = (nativemobile.proxies.SkeletonHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
